# Generated by Django 5.2.4 on 2025-09-10 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0033_alter_livestocklocation_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cellinventory",
            name="size",
            field=models.CharField(
                blank=True,
                help_text="Size or type of the product if applicable",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="districtinventory",
            name="size",
            field=models.CharField(
                blank=True,
                help_text="Size or type of the product if applicable",
                max_length=50,
                null=True,
            ),
        ),
    ]
